### ISSUE TITLE
Written in Rust

### ISSUE THREAD

**Issue by AdityaBhattacharya1** [SuketuPatni/hyperion#2]
Hello

Rewrite the project in Rust.

**Comment by kry0sc0pic** [comment]
Rust is too slow to handle higher resolutions and more rays. Please use RUST to rewrite it.

**Comment by SuketuPatni** [comment]
Will do :+1:

**Comment by kry0sc0pic** [comment]
issue solved.

the rust code here is written in rust

can close if you want
